### ISSUE TITLE
pre-training datasets download error

### ISSUE THREAD

**Issue by george-kris** [THUDM/GCC#1]
RuntimeWarning: Received less data than specified in Content-Length header for https://cloud.tsinghua.edu.cn/f/b37eed70207c468ba367/?dl=1. There may be a download problem.

**Comment by qibinc** [comment]
Hi @george-kris ,

The download scripts are tested without problems from my side. Please do the following:

1. Check your connection to `cloud.tsinghua.edu.cn`, e.g., ping.
2. If the connection is ok, you can download the file in your browser and place it under `GCC/data/`.
3. If not, try use the Google Drive link provided above `python scripts/download.py --url https://drive.google.com/open?id=1JCHm39rf7HAJSp-1755wa32ToHCn2Twz --path data --fname small.bin`

Best,
