### ISSUE TITLE
Questions about pretraining subgraphs

### ISSUE THREAD

**Issue by Kqiii** [THUDM/GCC#14]
Hi,

May I ask some questions about the pretraining subgraphs?

1.  Why do you apply a (** 0.75 ) operation to the individual node degrees? What is the benefit of this?
 https://github.com/THUDM/GCC/blob/20398aac95957784865d6c78bc46ead605221f0d/gcc/datasets/graph_dataset.py#L86

2. Here the "replace" option is set to True. 
https://github.com/THUDM/GCC/blob/20398aac95957784865d6c78bc46ead605221f0d/gcc/datasets/graph_dataset.py#L89
I believe it is likely that some nodes would be sampled twice or more times, which might harm the contrastive training process. For example, if node _v_ is sampled twice, then it would have two query-key pairs: (g_1, g_2) and (g_3, g_4) for _v_. In contrastive training (g_1, g_2) is regarded as a positive sample, while (g_1, g_3) is considered as negative, though all the four subgraphs, _i.e._, g_1 to g_4 are sampled from the ego-graph of node _v_. Would it be better if set this option to False? Or did I misunderstand anything about the contrastive training process?

3. Why there is a max(self.rw_hops, ....) operation? What is the disadvantage of just using the preset self.rw_hops for each of the nodes? Moreover, why is there also a (** 0.75) operation? 
https://github.com/THUDM/GCC/blob/20398aac95957784865d6c78bc46ead605221f0d/gcc/datasets/graph_dataset.py#L113

Thank you very much!

**Comment by Sanchez2020** [comment]
Hi, I also have a question. In `LoadBalanceGraphDataset`,  how is the `self.graphs` declared and assigned？ I did not see the relevant code.
https://github.com/THUDM/GCC/blob/20398aac95957784865d6c78bc46ead605221f0d/gcc/datasets/graph_dataset.py#L86

Thank you very much!
