### ISSUE TITLE
When  I run the algorithm get an error: "OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by Austinzhenghua** [THUDM/GCC#19]
Can someone tell me why and how to fix it, thanks a lot!

**Comment by qibinc** [comment]
Hi @Austinzhenghua ,

Thanks for your interest in this work. However, you question is not related to this repository. Please consider going to the following repos to ask a question:

https://github.com/pytorch/pytorch

https://github.com/NVIDIA/cuda-samples

Best,

**Comment by Austinzhenghua** [comment]
> Hi @Austinzhenghua ,
> 
> Thanks for your interest in this work. However, you question is not related to this repository. Please consider going to the following repos to ask a question:
> 
> https://github.com/pytorch/pytorch
> 
> https://github.com/NVIDIA/cuda-samples
> 
> Best,

Thanks a lot!

**Comment by hcmdgh** [comment]
So how do you fix the problem?
