### ISSUE TITLE
arpack error, retry= 0

### ISSUE THREAD

**Issue by JiangTanZJU** [THUDM/GCC#2]
When use your code and command "bash scripts/pretrain.sh <gpu> --moco --nce-k 16384" to train the model without any modification, the warning "arpack error, retry= 0" always occurs like this:
<img width="1232" alt="case" src="https://user-images.githubusercontent.com/39088437/85852120-8d56f680-b7e2-11ea-9693-fda31d7723c9.png">
And when I use your pretrained model to inference on my own dataset, this warning also occurs.
The relevant code is here:
https://github.com/THUDM/GCC/blob/dev/gcc/datasets/data_util.py#L249

Is it normal? Can I ignore it?

**Comment by qibinc** [comment]
Hi @JiangTanZJU ,

Please feel free to ignore this warning. We will comment it out later.

Best,
