### ISSUE TITLE
Can`t running this code with low equipments

### ISSUE THREAD

**Issue by ChloeWongxt** [THUDM/GCC#6]
Hi，Thank you for releasing your code. I am currently trying to reproduce the result of pre-training experiment on E2E.

However I can`t running this code because of my PC`s Configuration is too low.

Is there any methods to deal with it?

Maybe lower the parameters of the experiment? I have tried many times to lower the batch-size to 16. But it`s still can`t work. I have no idea to deal with it. 

How can i run this code with the following equipment?

I am looking forward to your reply. Thanks you very much.

My PC`s System parameters
![image](https://user-images.githubusercontent.com/41465616/88010727-29f18780-cb48-11ea-99a2-f9aaad19e0e0.png)

**Comment by qibinc** [comment]
Hi @ChloeWongxt ,

Please tell us what do you mean by "can't work". Is there any error raised during pretraining? For example, reducing the batch size will only work if it's an OOM error on GPU. If it's an OOM error on CPU, decreasing the `num_workers` argument might be a better way to save memory for the dataset loader.

Our pretraining requires a lot of computation CPU resources for matrix decomposition and it took 1 day on our 56-core Xeon(R) CPU E5-2680 v4 @ 2.40GHz so please expect the running time to be long. However, the experiments should be run without any errors with proper configuration. Please paste the specific error/reason preventing the experiments running here and we can see how to solve it.

**Comment by ChloeWongxt** [comment]
> Our pretraining requires a lot of computation CPU resources for matrix decomposition and it took 1 day on our 56-core

Thanks for your reply! 
There isn't any error when i run with the code.

But when i execute the following code, my computer crashed soon.
The mouse didn't move either. I had to reboot to get it back to normal use.

But I can`t get the result of pre-traing.

**Comment by qibinc** [comment]
Hi @ChloeWongxt ,

Thanks for your feedback. I apologize for the problem caused. It must be frustrating to see the computer crash every time you run the code. I suggest that you try the most low profile setting with:

```bash
bash scripts/pretrain.sh 0 --num-workers 1 --num-copies 1
```

This should consume minimum CPU and RAM on your machine. If this fails, I'm sorry that it's not possible to run pretraining on your machine. However, you can still download our pretrained models and evaluate it on downstream tasks https://github.com/THUDM/GCC/blob/master/GETTING_STARTED.md#download-pretrained-models.

**Comment by ChloeWongxt** [comment]
> ```shell
> bash scripts/pretrain.sh 0 --num-workers 1 --num-copies 1
> ```

Hi @qibinc 
Thanks for your patient and detailed rely!
I will try again.

**Comment by qibinc** [comment]
Hi @ChloeWongxt ,

I hope you're doing well. I will close this issue as it seems to be solved. If you meet any other issues on this topic, please feel free to reopen it.
